kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: prod
  namespace: multi-cluster

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: prod
  namespace: multi-cluster
  labels:
    env: prod
spec:
  fleetWorkspaceName: multi-cluster
  importedConfig:
    kubeConfigSecret: prod-kubeconfig
