kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: test
  namespace: multi-cluster

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: test
  namespace: multi-cluster
  labels:
    env: test
spec:
  fleetWorkspaceName: multi-cluster
  importedConfig:
    kubeConfigSecret: test-kubeconfig
