kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: examples
  namespace: multi-cluster
spec:
  repo: https://github.com/rancher/fleet-examples/
  paths:
  - simple
  - multi-cluster/manifests
  - multi-cluster/kustomize
  - multi-cluster/helm
  - multi-cluster/helm-kustomize
  targets:
  - name: all
    clusterGroup: all
